name: Run OMF tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: unit tests
        run: make docker-tests
      - name: check formatting
        run: make docker-format
      - name: pylint tests
        run: make docker-lint
      - name: docs tests
        run: make docker-docs
      - run: ls ./.coverage
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./.coverage
          verbose: true
